# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run.
on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

      # Generates the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # These are the options for dark mode snake
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'hsl(261, 64%, 42%)'
          background_color: 'hsl(220, 17%, 17%)'

      # Push the changes
      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # The branch where the generated files will be pushed
          target_branch: output
          # The directory where the generated files are located
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
